package handler

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"kart-challenge/backend/internal/model"
)

// --- Mocks ---

// MockProductRepository is a mock implementation of storage.ProductRepository
type MockProductRepository struct {
	mock.Mock
}

func (m *MockProductRepository) GetAllProducts() ([]model.Product, error) {
	args := m.Called()
	return args.Get(0).([]model.Product), args.Error(1)
}

func (m *MockProductRepository) GetProductByID(id string) (*model.Product, error) {
	args := m.Called(id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.Product), args.Error(1)
}

// MockOrderService is a mock implementation of the service layer
type MockOrderService struct {
	mock.Mock
}

func (m *MockOrderService) PlaceOrder(req model.OrderReq) (*model.Order, error) {
	args := m.Called(req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.Order), args.Error(1)
}

// --- Test Setup ---

// setupTestServer creates a new test server with mocked dependencies.
func setupTestServer(t *testing.T) (*Server, *MockProductRepository, *MockOrderService, *httptest.Server) {
	mockProductRepo := new(MockProductRepository)
	mockOrderService := new(MockOrderService)

	// The Server struct expects *service.OrderService and storage.ProductRepository
	// We use type casting to satisfy the interface for testing.
	server := &Server{
		OrderService: mockOrderService,
		ProductRepo:  mockProductRepo,
	}

	r := chi.NewRouter()
	// HandlerFromMux is generated by oapi-codegen
	HandlerFromMux(server, r)

	ts := httptest.NewServer(r)
	t.Cleanup(ts.Close)

	return server, mockProductRepo, mockOrderService, ts
}

// Helper functions for pointers
func sPtr(s string) *string   { return &s }
func fPtr(f float32) *float32 { return &f }

// --- Test Cases ---

func TestListProducts(t *testing.T) {
	_, mockProductRepo, _, ts := setupTestServer(t)

	t.Run("Success", func(t *testing.T) {
		expectedProducts := []model.Product{
			{Id: sPtr("1"), Name: sPtr("Product A"), Price: fPtr(10.0)},
			{Id: sPtr("2"), Name: sPtr("Product B"), Price: fPtr(20.0)},
		}
		mockProductRepo.On("GetAllProducts").Return(expectedProducts, nil).Once()

		resp, err := http.Get(ts.URL + "/product")
		assert.NoError(t, err)
		defer resp.Body.Close()

		assert.Equal(t, http.StatusOK, resp.StatusCode)
		assert.Equal(t, "application/json", resp.Header.Get("Content-Type"))

		var actualProducts []model.Product
		err = json.NewDecoder(resp.Body).Decode(&actualProducts)
		assert.NoError(t, err)
		assert.Equal(t, expectedProducts, actualProducts)

		mockProductRepo.AssertExpectations(t)
	})

	t.Run("Internal Server Error", func(t *testing.T) {
		mockProductRepo.On("GetAllProducts").Return([]model.Product{}, errors.New("db error")).Once()

		resp, err := http.Get(ts.URL + "/product")
		assert.NoError(t, err)
		defer resp.Body.Close()

		assert.Equal(t, http.StatusInternalServerError, resp.StatusCode)
		mockProductRepo.AssertExpectations(t)
	})
}

func TestGetProduct(t *testing.T) {
	_, mockProductRepo, _, ts := setupTestServer(t)

	t.Run("Success", func(t *testing.T) {
		productID := "10"
		expectedProduct := model.Product{Id: sPtr(productID), Name: sPtr("Waffle"), Price: fPtr(13.3)}
		mockProductRepo.On("GetProductByID", productID).Return(&expectedProduct, nil).Once()

		resp, err := http.Get(ts.URL + "/product/" + productID)
		assert.NoError(t, err)
		defer resp.Body.Close()

		assert.Equal(t, http.StatusOK, resp.StatusCode)
		assert.Equal(t, "application/json", resp.Header.Get("Content-Type"))

		var actualProduct model.Product
		err = json.NewDecoder(resp.Body).Decode(&actualProduct)
		assert.NoError(t, err)
		assert.Equal(t, expectedProduct, actualProduct)

		mockProductRepo.AssertExpectations(t)
	})

	t.Run("Not Found", func(t *testing.T) {
		productID := "999"
		// The repository returns an error, which the handler translates to 404
		mockProductRepo.On("GetProductByID", productID).Return(nil, errors.New("product with ID 999 not found")).Once()

		resp, err := http.Get(ts.URL + "/product/" + productID)
		assert.NoError(t, err)
		defer resp.Body.Close()

		assert.Equal(t, http.StatusNotFound, resp.StatusCode)
		mockProductRepo.AssertExpectations(t)
	})
}

func TestPlaceOrder(t *testing.T) {
	_, _, mockOrderService, ts := setupTestServer(t)

	// Define a sample request and response
	orderReq := model.OrderReq{
		Items: []struct {
			ProductId string `json:"productId"`
			Quantity  int    `json:"quantity"`
		}{
			{ProductId: "10", Quantity: 2},
		},
	}
	orderRes := model.Order{
		Id:        sPtr("uuid-123"),
		Total:     fPtr(26.6),
		Discounts: fPtr(0.0),
	}

	// Helper to create a request body
	createReqBody := func(req model.OrderReq) *bytes.Buffer {
		body, _ := json.Marshal(req)
		return bytes.NewBuffer(body)
	}

	t.Run("Success", func(t *testing.T) {
		reqBody := createReqBody(orderReq)
		mockOrderService.On("PlaceOrder", orderReq).Return(&orderRes, nil).Once()

		resp, err := http.Post(ts.URL+"/order", "application/json", reqBody)
		assert.NoError(t, err)
		defer resp.Body.Close()

		assert.Equal(t, http.StatusOK, resp.StatusCode)
		assert.Equal(t, "application/json", resp.Header.Get("Content-Type"))

		var actualOrder model.Order
		err = json.NewDecoder(resp.Body).Decode(&actualOrder)
		assert.NoError(t, err)
		assert.Equal(t, *orderRes.Id, *actualOrder.Id)
		assert.Equal(t, *orderRes.Total, *actualOrder.Total)

		mockOrderService.AssertExpectations(t)
	})

	t.Run("Invalid Request Body", func(t *testing.T) {
		// Send non-JSON body
		resp, err := http.Post(ts.URL+"/order", "application/json", bytes.NewBufferString("invalid json"))
		assert.NoError(t, err)
		defer resp.Body.Close()

		assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	})

	t.Run("Invalid Promo Code Error", func(t *testing.T) {
		reqWithCoupon := orderReq
		reqWithCoupon.CouponCode = sPtr("BADCODE")
		reqBody := createReqBody(reqWithCoupon)

		// The handler checks for the error string "invalid coupon code"
		errMsg := fmt.Sprintf("invalid coupon code: %s", *reqWithCoupon.CouponCode)
		mockOrderService.On("PlaceOrder", reqWithCoupon).Return(nil, errors.New(errMsg)).Once()

		resp, err := http.Post(ts.URL+"/order", "application/json", reqBody)
		assert.NoError(t, err)
		defer resp.Body.Close()

		assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
		mockOrderService.AssertExpectations(t)
	})

	t.Run("Product Not Found Error", func(t *testing.T) {
		reqBody := createReqBody(orderReq)

		// The handler checks for the error string "product not found"
		errMsg := "product not found: 999"
		mockOrderService.On("PlaceOrder", orderReq).Return(nil, errors.New(errMsg)).Once()

		resp, err := http.Post(ts.URL+"/order", "application/json", reqBody)
		assert.NoError(t, err)
		defer resp.Body.Close()

		// Handler should return 400 for this specific error
		assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
		mockOrderService.AssertExpectations(t)
	})

	t.Run("Internal Server Error", func(t *testing.T) {
		reqBody := createReqBody(orderReq)
		mockOrderService.On("PlaceOrder", orderReq).Return(nil, errors.New("database connection failed")).Once()

		resp, err := http.Post(ts.URL+"/order", "application/json", reqBody)
		assert.NoError(t, err)
		defer resp.Body.Close()

		assert.Equal(t, http.StatusInternalServerError, resp.StatusCode)
		mockOrderService.AssertExpectations(t)
	})
}
