// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "kart-challenge/backend/internal/model"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Place an order
	// (POST /order)
	PlaceOrder(w http.ResponseWriter, r *http.Request)
	// List products
	// (GET /product)
	ListProducts(w http.ResponseWriter, r *http.Request)
	// Find product by ID
	// (GET /product/{productId})
	GetProduct(w http.ResponseWriter, r *http.Request, productId int64)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Place an order
// (POST /order)
func (_ Unimplemented) PlaceOrder(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List products
// (GET /product)
func (_ Unimplemented) ListProducts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Find product by ID
// (GET /product/{productId})
func (_ Unimplemented) GetProduct(w http.ResponseWriter, r *http.Request, productId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PlaceOrder operation middleware
func (siw *ServerInterfaceWrapper) PlaceOrder(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, externalRef0.Api_keyScopes, []string{"create_order"})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlaceOrder(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListProducts operation middleware
func (siw *ServerInterfaceWrapper) ListProducts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetProduct operation middleware
func (siw *ServerInterfaceWrapper) GetProduct(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "productId" -------------
	var productId int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "productId", runtime.ParamLocationPath, chi.URLParam(r, "productId"), &productId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProduct(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/order", wrapper.PlaceOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/product", wrapper.ListProducts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/product/{productId}", wrapper.GetProduct)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RWb48TNxP/Kpaf5wWVkmzCoUrNO8oVOLXSne5KK3RE4HhnN+a8HmOPD1K0372ynU02",
	"yQZQOd7cbezx/PnNzG/mM5fYWDRgyPP5Z+7lChqRPi9dCS5+WIcWHClIx6XyEsNGHD6Jxup4cTubLkac",
	"1hb4nJvQLMHxdsRVeSDGp9PpdLz/h+9eenLK1OklQZNsbD/2/bAOyyDpIhkowUunLCk0fM4vzhlWjFbA",
	"NkJ8QP+HIAwpWg88J2hYinH3ThmCOobUbo9w+R4k8d2BcE6s4++N1X3v/++g4nP+v2IHeLFBu7jauDmg",
	"i5CEPsDwlwGoh/xKGbyGD8chXmkhgQlm4CPDlOfRAbwSg0XzDEs4fn2ZPoSO8DbIJJbAhLVaQckIE/Cd",
	"0n7mXz69unr98vrmh6ebPXLwISgH5U//NfODKvpF0F3HwHa+9ZQvvlooB1py4EPPuvI4AkUKghrd+rDH",
	"/hZVpWEY56OGnJ3ov0bUMND+4O8I7aGSFZH186JIea8QSzRaGZiUYHBSwn1hw1IrWSStPv8bf0xujjcq",
	"J+9tPehJg0ul4SEtZo0nDZJYaqCHNJg1nja4Cs3SCKUf1Gan9ITZIcYwojkC+tlKyTsw7AtFZZ2SAzxx",
	"A1orU7N8vUcGs7PJ2WLEK3SNID7nlUbRo9vTrNaOuAcZnKL1TWTPXJXCqrd3kPpARcsrEJl/ckDb+10L",
	"WvU7xB5so1sEzgh9jtIfB/FcmZJhINagAyaW8TNyjVwJrcHUMbDgdDRKZOdF4T+KugY3UZjayFR4rPTP",
	"lfJMeSYYjCU2DTgJ7OnVBVsKDyVDk0xcWjDx8GwyY96CVJWSImqYMPYaA5PCsOrYvTfmjXnls747WLN3",
	"wioCT+/ixQ02wIKHKmimlbnz8zdmzG6vwaJXhG69eNQVXa1oFZYTiU2BqBWOa4fBFpVDQ2Mw5VgKR4ke",
	"FcX+zPOGPUcs2WWqUzbux8BH/B6czwjMJtPJNAKEFoywis/52WQ2mcZBJGiVEpHLPnEQevqGKcZUBs4T",
	"upiXSFwJsDg2svjlZjBF5gVPv2K5zuPOEBjKtWT1BufivY+GurXoa2N8O2/bNpO7t2h8rtDH0+nD2sm1",
	"uw+ID1KC9zG329Ajxk+y8YNhZ+6FViVTxgbKUrNjqVdGBFqhU/9AmYXOBnoE3VKVJWRjjx8fS/wVTSV/",
	"GHySkI/7zcznt702vuXSgSB4mytg0S5G3IemEXHWdXk32y2DRJ2oqpNuR7ywu6FZw0DxvABiQutuZ/BM",
	"3AulI0+zCt1W9X4J/aE8XXXb3Xdm+Ps2w29NftsHLrq/DbiHW4fVHnLF5+1e055E8RooOBOJzCtT6/7G",
	"vY/cC+iASx3uRAMEzqe0D61z3SpHyFyywUeZ2iM77Ii9v3rtlilyAUY9qLdjRhn6+cnQQrf4ge26zeED",
	"NezFOfMhr9tZ9skANW7gM0iswmDKg0pIU63DeLlmF+fD5ZA61N13mdoNui9uJZHPI6QbhYfO/XYPbk2r",
	"uBrkedoryf288nY0TPqJAj3uHuR+bRftvwEAAP//JlYsOdIOAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
