// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package handler

const (
	Api_keyScopes = "api_key.Scopes"
)

// Order defines model for Order.
type Order struct {
	Discounts *float32 `json:"discounts,omitempty"`
	Id        *string  `json:"id,omitempty"`
	Items     *[]struct {
		// ProductId ID of the product
		ProductId *string `json:"productId,omitempty"`

		// Quantity Item count
		Quantity *int `json:"quantity,omitempty"`
	} `json:"items,omitempty"`
	Products *[]Product `json:"products,omitempty"`
	Total    *float32   `json:"total,omitempty"`
}

// OrderReq Place a new order
type OrderReq struct {
	// CouponCode Optional promo code applied to the order
	CouponCode *string `json:"couponCode,omitempty"`
	Items      []struct {
		// ProductId ID of the product (required)
		ProductId string `json:"productId"`

		// Quantity Item count (required)
		Quantity int `json:"quantity"`
	} `json:"items"`
}

// Product defines model for Product.
type Product struct {
	Category *string `json:"category,omitempty"`
	Id       *string `json:"id,omitempty"`
	Image    *struct {
		Desktop   *string `json:"desktop,omitempty"`
		Mobile    *string `json:"mobile,omitempty"`
		Tablet    *string `json:"tablet,omitempty"`
		Thumbnail *string `json:"thumbnail,omitempty"`
	} `json:"image,omitempty"`
	Name *string `json:"name,omitempty"`

	// Price Selling price
	Price *float32 `json:"price,omitempty"`
}

// PlaceOrderJSONRequestBody defines body for PlaceOrder for application/json ContentType.
type PlaceOrderJSONRequestBody = OrderReq
